# Generated by Django 5.0 on 2024-01-08 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0005_alter_car_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='feature',
            options={'ordering': ['name']},
        ),
        migrations.AddField(
            model_name='car',
            name='availability_date_en',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='car',
            name='availability_date_tr',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='car',
            name='category_en',
            field=models.CharField(choices=[('Luxury', 'Luxury'), ('Econom', 'Econom')], max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='car',
            name='category_tr',
            field=models.CharField(choices=[('Luxury', 'Luxury'), ('Econom', 'Econom')], max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='car',
            name='features_en',
            field=models.ManyToManyField(null=True, to='cars.feature'),
        ),
        migrations.AddField(
            model_name='car',
            name='features_tr',
            field=models.ManyToManyField(null=True, to='cars.feature'),
        ),
        migrations.AddField(
            model_name='car',
            name='image_en',
            field=models.ImageField(null=True, upload_to='car_images/'),
        ),
        migrations.AddField(
            model_name='car',
            name='image_tr',
            field=models.ImageField(null=True, upload_to='car_images/'),
        ),
        migrations.AddField(
            model_name='car',
            name='name_en',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='car',
            name='name_tr',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='car',
            name='price_en',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='car',
            name='price_tr',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='feature',
            name='name',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
