# Generated by Django 5.0 on 2024-01-08 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0009_alter_car_features'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='feature',
            options={'ordering': ['id'], 'verbose_name': 'Hizmet', 'verbose_name_plural': 'Hizmetler'},
        ),
        migrations.AlterField(
            model_name='car',
            name='features',
            field=models.ManyToManyField(to='cars.feature'),
        ),
    ]
