# Generated by Django 5.0 on 2024-01-08 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0010_alter_feature_options_alter_car_features'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='features',
            field=models.ManyToManyField(to='cars.feature', verbose_name='Arabanin ozel hizmeti'),
        ),
    ]
