# Generated by Django 5.0 on 2024-01-08 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0011_alter_car_features'),
    ]

    operations = [
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(null=True, upload_to='car_images_album/', verbose_name='Araç resmi')),
            ],
            options={
                'verbose_name': 'Araçlarin albüm resimi',
                'verbose_name_plural': 'Araçin albüm resimleri',
                'ordering': ['id'],
            },
        ),
        migrations.AlterModelOptions(
            name='car',
            options={'ordering': ['id'], 'verbose_name': 'Araç', 'verbose_name_plural': 'Araçlar'},
        ),
        migrations.AlterModelOptions(
            name='feature',
            options={'ordering': ['id'], 'verbose_name': 'Araç hizmeti', 'verbose_name_plural': 'Araç hizmetleri'},
        ),
        migrations.AlterField(
            model_name='car',
            name='availability_date',
            field=models.DateField(verbose_name='Araçin mevcut tarihi'),
        ),
        migrations.AlterField(
            model_name='car',
            name='category',
            field=models.CharField(choices=[('Luxury', 'Luxury'), ('Econom', 'Econom')], max_length=100, verbose_name='Araçin kategorisi'),
        ),
        migrations.AlterField(
            model_name='car',
            name='features',
            field=models.ManyToManyField(to='cars.feature', verbose_name='Araçin ozel hizmeti'),
        ),
        migrations.AlterField(
            model_name='car',
            name='image',
            field=models.ImageField(null=True, upload_to='car_images/', verbose_name='Araçin resmi'),
        ),
        migrations.AlterField(
            model_name='car',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Araçin Ismi'),
        ),
        migrations.AlterField(
            model_name='car',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Araçin fiyati'),
        ),
        migrations.AlterField(
            model_name='feature',
            name='name',
            field=models.CharField(max_length=255, unique=True, verbose_name='Araç hizmetinin ismi'),
        ),
        migrations.AddField(
            model_name='car',
            name='photo_album',
            field=models.ManyToManyField(blank=True, to='cars.photo', verbose_name='Araçin foto albümü'),
        ),
    ]
