# Generated by Django 5.0 on 2024-01-08 16:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0006_alter_feature_options_car_availability_date_en_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='car',
            name='availability_date_en',
        ),
        migrations.RemoveField(
            model_name='car',
            name='availability_date_tr',
        ),
        migrations.RemoveField(
            model_name='car',
            name='category_en',
        ),
        migrations.RemoveField(
            model_name='car',
            name='category_tr',
        ),
        migrations.RemoveField(
            model_name='car',
            name='features_en',
        ),
        migrations.RemoveField(
            model_name='car',
            name='features_tr',
        ),
        migrations.RemoveField(
            model_name='car',
            name='image_en',
        ),
        migrations.RemoveField(
            model_name='car',
            name='image_tr',
        ),
        migrations.RemoveField(
            model_name='car',
            name='name_en',
        ),
        migrations.RemoveField(
            model_name='car',
            name='name_tr',
        ),
        migrations.RemoveField(
            model_name='car',
            name='price_en',
        ),
        migrations.RemoveField(
            model_name='car',
            name='price_tr',
        ),
    ]
