# Generated by Django 5.0 on 2024-01-08 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0007_remove_car_availability_date_en_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='car',
            options={'ordering': ['id'], 'verbose_name': 'Araba', 'verbose_name_plural': 'Arabalar'},
        ),
        migrations.AlterModelOptions(
            name='feature',
            options={'ordering': ['name'], 'verbose_name': 'Hizmet', 'verbose_name_plural': 'Hizmetler'},
        ),
        migrations.AlterField(
            model_name='car',
            name='availability_date',
            field=models.DateField(verbose_name='Arabanin mevcut tarihi'),
        ),
        migrations.AlterField(
            model_name='car',
            name='category',
            field=models.CharField(choices=[('Luxury', 'Luxury'), ('Econom', 'Econom')], max_length=100, verbose_name='Arabanin kategorisi'),
        ),
        migrations.AlterField(
            model_name='car',
            name='features',
            field=models.ManyToManyField(to='cars.feature', verbose_name='Arabanin ozel hizmetleri'),
        ),
        migrations.AlterField(
            model_name='car',
            name='image',
            field=models.ImageField(null=True, upload_to='car_images/', verbose_name='Arabanin resmi'),
        ),
        migrations.AlterField(
            model_name='car',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Arabanin Ismi'),
        ),
        migrations.AlterField(
            model_name='car',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Arabanin fiyati'),
        ),
        migrations.AlterField(
            model_name='feature',
            name='name',
            field=models.CharField(max_length=255, unique=True, verbose_name='Hizmetin Ismi'),
        ),
    ]
