# Generated by Django 5.0 on 2024-01-15 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0012_photo_alter_car_options_alter_feature_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='feature',
            name='icon',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Icon'),
        ),
    ]
