# Generated by Django 5.0 on 2024-01-15 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0013_feature_icon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feature',
            name='icon',
            field=models.FileField(blank=True, null=True, upload_to='icons/', verbose_name='Icon'),
        ),
    ]
