# Generated by Django 5.0 on 2024-01-15 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0014_alter_feature_icon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feature',
            name='icon',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Icon'),
        ),
    ]
