# Generated by Django 5.0 on 2024-01-16 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0015_alter_feature_icon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feature',
            name='icon',
            field=models.FileField(blank=True, null=True, upload_to='icons/', verbose_name='Icon'),
        ),
    ]
