# Generated by Django 5.0 on 2024-01-20 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0017_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='photo_album',
            field=models.ManyToManyField(blank=True, related_name='cars', to='cars.photo', verbose_name='Araçin foto albümü'),
        ),
    ]
